### ISSUE TITLE
Problem with js

### ISSUE THREAD

**Issue by wwillm** [jelicanin/silverstripe-cookie-policy-notification#3]
I installed the module with composer and put my settings.
But when I call my homepage, I do not see anything.
Inspecting with chrome gives me the emssage:

   Uncaught TypeError: $(...).cookieNotify is not a function

When I look to the sources tab, I see:
        <script type="text/javascript" src="/framework/thirdparty/jquery/jquery.js?m=1428661025"></script><script type="text/javascript" src="/cookie-policy-notification/javascript/jquery.cookie.policy.js?m=1429084899"></script><script type="text/javascript">//<![CDATA[
$(document).ready(function() {
	$('body').cookieNotify({btnText: 'Cookie Warnung', text: '<p>Bla bla </p><p>Bla Bla 2</p>', position: 'top'});
});

All seems to be OK, I do not see any erroneous code. Can someone help me?

**Comment by wwillm** [comment]
It was a double definition of jquery.js, I removed the jquery Requirement in code/CookiePolicy.php
So we can close this issue

**Comment by wwillm** [comment]
As written before.

**Comment by mkstepan** [comment]
Hello, i've got the same issue here (not showing anything on page), could you explain what exactly you removed?
